apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-splunk
spec:
  selector:
    app: splunk
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
